/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard-scss', 'stylelint-config-recommended-vue/scss'],
  plugins: ['stylelint-order'],
  rules: {
    'selector-class-pattern': null,
    'selector-pseudo-class-no-unknown': [true, { ignorePseudoClasses: ['deep', 'global'] }],
    'scss/at-rule-no-unknown': [true, { ignoreAtRules: ['use', 'tailwind', 'apply'] }],
    'no-descending-specificity': null,
    'number-max-precision': 4,
    'string-quotes': 'single',
    'color-hex-length': 'short',
    'color-named': 'never',
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'flex',
      'flex-direction',
      'justify-content',
      'align-items',
      'width',
      'height',
      'margin',
      'padding',
      'border',
      'background',
      'color',
      'font',
      'transition',
    ],
  },
}
